image:
  #- Visual Studio 2015
  #- Visual Studio 2017
  - Visual Studio 2019

environment:
  global:
    TZ: Europe/Warsaw
  matrix:
    - arch: x86_64
      bits: 64

install:
  - set MSYS_SH=C:\msys64\usr\bin\sh.exe
  - set MSYSTEM=MINGW%BITS%
  - set TEST=win%BITS%

# scripts to run before build
before_build:

build_script:
  - '%MSYS_SH% --login -c ". /etc/profile && cd $APPVEYOR_BUILD_FOLDER && ./test.sh'

#test_script:
#  - '%MSYS_SH% --login -c ". /etc/profile && cd /c/OpenSSL-$TEST && ls -lR"'

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:

  # pushing a single file
  - path: openssl-win32.tar.gz
  - path: openssl-win64.tar.gz
