clone_depth: 50

image:
  #- Visual Studio 2015
  #- Visual Studio 2017
  - Visual Studio 2019

environment:
  global:
    TZ: Europe/Zurich
  matrix:
    - arch: x86_64
      bits: 64
    - arch: i686
      bits: 32

install:
  - set MSYS_SH=C:\msys64\usr\bin\sh.exe
  - set MSYSTEM=MINGW%BITS%
  - set TEST=win%BITS%

# scripts to run before build
before_build:

build_script:
  - '%MSYS_SH% --login -c ". /etc/profile && cd $APPVEYOR_BUILD_FOLDER && pwd && tar czf openssl-$TEST.tar.gz -C /c/ OpenSSL-$TEST"'

test_script:
  - '%MSYS_SH% --login -c ". /etc/profile && cd /c && ls -lR"'
